spring.application.name=prueba_tecnica

# ==========================
# Configuraciones de JPA + MySQL
# ==========================
spring.datasource.url=jdbc:h2:mem:prueba_tecnica;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
server.port=8080